spring.application.name=networktraffic
spring.datasource.url=jdbc:postgresql://localhost:5432/networkDB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

anomaly.window-seconds=10
anomaly.cooldown-seconds=60
anomaly.traffic-spike.packet-count=100
anomaly.port-scan.unique-ports=20
anomaly.syn-flood.syn-count=50
anomaly.large-packet.bytes=1400
anomaly.dns-volume.packet-count=50